CONFIG_DEBUG=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_DEBUG_COREDUMP=y
CONFIG_ASSERT=y
CONFIG_ASSERT_LEVEL=2
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_SCHED_THREAD_USAGE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_SEGGER_RTT_SECTION_NONE=y
CONFIG_CONSOLE=y
CONFIG_STDOUT_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_ZBUS_LOG_LEVEL_INF=y
CONFIG_PWM_LOG_LEVEL_ERR=y
CONFIG_HW_STACK_PROTECTION=y
CONFIG_EXTRA_EXCEPTION_INFO=y