services:
  zephyr-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      
    volumes:      
      # Mount your local project into the workspace
      - ..:/workdir/CAR-STM:cached
      - /dev:/dev
      
      # Create a persistent volume for the build cache
      - zephyr-ccache:/home/user/.ccache

    environment:
      - USE_CCACHE=1
    
    privileged: true
    
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  zephyr-ccache:
  zephyr-workspace: